language = "english_1"

hours = [
  'twelve',
  'one',
  'two',
  'three',
  'four',
  'five',
  'six',
  'seven',
  'eight',
  'nine',
  'ten',
  'eleven',
  'whats wrong with the hours'
]

minutes = [
  'five past',
  'ten past',
  'quarter past',
  'twenty past',
  'twenty-five past',
  'kalf past',
  'twenty-five to',
  'twenty to',
  'quarter to',
  'ten to',
  'five to',
  'minute error'
]

prepositions = [
  ['almost', 'nearly'],
  ['exactly', 'precisely', 'now', ''],
  ['just after', 'right after', 'shortly after','about','around'],
  ['Aigain, what??']
]


special_cases = [
  "It’s ’round about midnight.",
  "It’s midnight.",
  "It’s ’round about midnight.",
  "It's two to one.",
  "It's one to one.",
  "It's exactly one.",
  "It's one past one.",
  "It's two past one.",
  "It’s noon."
]

#onTheHourTemplate = "It’s {{ p }} {{ h }} o’clock."
#template = "It’s {{ p }} {{ m }} {{ h }}."

#ADD_TEXT = [
#   "* Time to dance."
#]
